### ISSUE TITLE
how to handle pdf-theme in adoc2pdf?

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/adoc2pdf#1]
Please let's discuss where we want to locate our custom pdf theme:

* it's currently a distinct github repository, which is
* included as submodule in foundation/template curriculum

* we might include this (pdf-theme) repo as submodule ALSO in adoc2pdf

* or shall we simply delete the theme HERE and require that it's always included

Opinion?

**Comment by p-goetz** [comment]
I think with the new Gradle way of building things the adoc2pdf module is not needed any more. Since we use the Gradle wrapper so it is not necessary to have Gradle or asciidoctor installed on the build host and only expect a JRE, I think this could be deleted.

**Comment by gernotstarke** [comment]
+1. Let's keep the repository - but let's remove the submodule from template and foundation curriculum.

**Comment by gernotstarke** [comment]
but: we need to adjust the travis build too... is it currently requires adoc2pdf.
